const data = {
  competitionDoing: [
    {
        img: require('./images/img1.png'),
        teamOne: '清华',
        teamTwo: '浙大',
        teamOneScore: 1,
        teamTwoScore: 2,
        startTime: '2019.07.17 12:00',
        wager: 0,
        liveUrl: 'http://127.0.0.1:8080',
        logUrl: '',
    },
    {
        img: require('./images/img1.png'),
        teamOne: 'CMU',
        teamTwo: '中科大',
        teamOneScore: 1,
        teamTwoScore: 2,
        startTime: '2019.07.17 12:05',
        wager: 0,
        liveUrl: '',
        logUrl: '',
    },
    {
        img: require('./images/img1.png'),
        teamOne: '东京大学',
        teamTwo: '清华',
        teamOneScore: 1,
        teamTwoScore: 2,
        startTime: '2019.07.17 12:10',
        wager: 0,
        liveUrl: '',
        logUrl: '',
      },
      {
        img: require('./images/img1.png'),
        teamOne: 'CMU',
        teamTwo: '东南大学',
        teamOneScore: 1,
        teamTwoScore: 2,
        startTime: '2019.07.17 12:03',
        wager: 0,
        liveUrl: '',
      },
  ],
  competitionDone: [
    {
      img: require('./images/img1.png'),
      teamOne: '清华',
      teamTwo: '浙大',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.09 02:00',
      wager: 0,
      liveUrl: 'http://127.0.0.1:8080',
      logUrl: '',
  },
  {
      img: require('./images/img1.png'),
      teamOne: 'CMU',
      teamTwo: '中科大',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.01 18:00',
      wager: 0,
      liveUrl: '',
      logUrl: '',
  },
  {
      img: require('./images/img1.png'),
      teamOne: '东京大学',
      teamTwo: '清华',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.02 12:00',
      wager: 0,
      liveUrl: '',
      logUrl: '',
    },
    {
      img: require('./images/img1.png'),
      teamOne: 'CMU',
      teamTwo: '东南大学',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.06.09 12:00',
      wager: 0,
      liveUrl: '',
    },
  ],
  competitionToDo: [
    {
      img: require('./images/img1.png'),
      teamOne: '清华',
      teamTwo: '浙大',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.17 12:00',
      wager: 0,
      liveUrl: 'http://127.0.0.1:8080',
      logUrl: '',
  },
  {
      img: require('./images/img1.png'),
      teamOne: 'CMU',
      teamTwo: '中科大',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.17 14:00',
      wager: 0,
      liveUrl: '',
      logUrl: '',
  },
  {
      img: require('./images/img1.png'),
      teamOne: '东京大学',
      teamTwo: '清华',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.17 18:00',
      wager: 0,
      liveUrl: '',
      logUrl: '',
    },
    {
      img: require('./images/img1.png'),
      teamOne: 'CMU',
      teamTwo: '东南大学',
      teamOneScore: 1,
      teamTwoScore: 2,
      startTime: '2019.07.17 22:00',
      wager: 0,
      liveUrl: '',
    },
  ],
};

export default data;
